version: "3.3"

services:
  mc-serv:
    image: ${IMAGE}
    container_name: ${CONTAINER_NAME}
    env_file: ./spygot/.env
    build:
      context: ./spygot
      args:
        - IMAGE
        - SPIGOT_VER
        - ENTRYPOINT_FILE
        - SPYGOT_CONF_PATH
        - CONFIG_FILE
        - EULA_FILE
        - SERVER_PATH
        - RAM
    ports:
      - "${PORT_SERV_OUT}:${PORT_SERV_IN}"

  #mc-proxy:
  #  image: sapmachine:latest
  #  container_name: mc-proxy
  #  depends_on:
  #    - mc-serv
  #  build:
  #    context: ./velocity
  #    args:
  #      - IMAGE=sapmachine:latest
  #      - ENTRYPOINT_FILE
  #      - VELOCITY_FILE_PATH
  #  env_file: ./velocity/.env
  #  ports:
  #    - "25577:25577"
